- name: install nginx
  ansible.builtin.shell: dnf install nginx -y

- name: enable and start nginx
  ansible.builtin.systemd.service:
    - name: nginx
      state: restarted
      daemon_reload: true
      enabled: true