- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Install unzip package
  ansible.builtin.dnf:
    name: unzip
    state: present

- name: Copy nginx configuration file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Delete existing nginx data
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create file for Nginx data
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download frontend app code
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: enable and start nginx
  ansible.builtin.systemd:
     name: nginx
     daemon_reload: yes
     state: restarted
     enabled: true
