- name: Install mysql
  ansible.builtin.dnf.dnf:
    name: mysql-server
    state: installed

- name: Start and enable mysql
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: set password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

